FROM debian:jessie

RUN apt-get update && apt-get install -y postgresql-9.6

# run the postgres as the postgres user created by the postgres-9.6 package when it was installed
USER postgres

# create mechanik role w/ password & database owned by role
RUN /etc/init.d/postgresql start &&\
    psql --command "CREATE USER mechanik WITH SUPERUSER PASSWORD 'mechanik';" &&\
    createdb -O mechanik mechanik

USER root

RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/9.6/main/pg_hba.conf  &&\
    echo "listen_addresses='*'" >> /etc/postgresql/9.6/main/postgresql.conf

EXPOSE 5432

# add VOLUMEs to allow backup of config, logs and databases
VOLUME ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

# run!
CMD ["/usr/lib/postgresql/9.6/bin/postgres", "-D", "/var/lib/postgresql/9.6/main", "-c", "config_file=/etc/postgresql/9.6/main/postgresql.conf"]


## references
## http://www.postgresql.org/download/linux/debian/
## https://github.com/andreagrandi/postgresql-docker/blob/master/Dockerfile
## https://github.com/docker-library/postgres/blob/master/9.6/Dockerfile
## https://github.com/sameersbn/docker-postgresql/blob/master/Dockerfile
## https://hub.docker.com/_/postgres/